name: Terraform Plan POS-TECH SOAT CI/CD

on:
  push:
  workflow_dispatch:

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform import state
        run: terraform import aws_s3_bucket.state fiap-soat-tc-terraform

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Upload do plano
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: tfplan
